language: android
dist: trusty
jdk: oraclejdk8
sudo: false

env:
    global:
        - ANDROID_API_LEVEL=28
        - API=25
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3
        - ADB_INSTALL_TIMEOUT=20
        - ABI=armeabi-v7a

matrix:
   #- API=15 # only runs locally. Create+Start once from AndroidStudio to init sdcard. Then only from command-line w/-engine classic
   - API=16 AUDIO=-no-audio
   - API=17
   - API=18 # API18 has started being flaky
   #- API=19 # Kernel/emulator mismatch failure probably fixible with -engine classic
   # API 20 was Android Wear only
   - API=21 ABI=x86_64
   - API=22 ABI=x86_64
   - API=23 ABI=x86_64
   - API=24 ABI=x86_64
   - API=25 ABI=x86_64 
   #- API=26 ABI=x86_64 # Fails with unrecognized tests? orchestrator change or something?
   - API=27 ABI=x86_64

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-$ABI-google-apis-$API
    #- sys-img-armeabi-v7a-android-17

cache:
    directories:
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
        - "$HOME/.android/build-caches/"

# Emulator Management: Create, Start and Wait
before_script:
    - android list targets
    - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI -tag "google-apis"
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - ./gradlew dependencyCheckAnalyze build
    - adb shell input keyevent 82
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

notifications:
  slack: brute-force-workspace:92Ym0s6dAX8K2zByShEuFcuy