language: android
dist: trusty
jdk: oraclejdk8
sudo: false

env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_EMULATOR_LEVEL=25
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3
        - ADB_INSTALL_TIMEOUT=20
        - ANDROID_ABI=x86_64

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-$ANDROID_ABI-google-apis-$ANDROID_EMULATOR_LEVEL
    #- sys-img-armeabi-v7a-android-17

cache:
    directories:
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
        - "$HOME/.android/build-caches/"

# Emulator Management: Create, Start and Wait
before_script:
    - android list targets
    - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI -tag "google-apis"
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - ./gradlew dependencyCheckAnalyze build
    - adb shell input keyevent 82
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

notifications:
  slack: brute-force-workspace:92Ym0s6dAX8K2zByShEuFcuy